name: Deploy Nodejs Docker CI/CD on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd /home/ubuntu/DevOps_FullCourse/05_CICD/01_GitHub-Actions/01_express-weatherapp

            echo "Pulling latest code..."
            git pull origin main

            echo "Stopping old containers..."
            docker compose down

            echo "Building and starting new containers..."
            docker compose up -d --build

            echo "Deployment completed!"
